[package]
name = "types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"  # To (de)serialize enums with a #repr(u8/i8/etc.)
nalgebra = "0.31"
